name: frontier
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip
  - setuptools>=68
  - wheel
  - numpy>=1.23,<3
  - pandas>=1.5,<3
  - scipy>=1.9,<2
  - scikit-learn>=1.1,<2
  - plotly>=5,<7
  - tqdm>=4.64,<5
  - pyyaml>=6,<7
  - pytest>=7,<9
  - fasteners>=0.19,<1
  - pip:
      - ddsketch>=3,<4
