"""Parity case definitions for the 15-case test matrix."""

from tests.e2e.pd_af_parity.harness import ParityCaseConfig, ParityLayer


PARITY_CASES = [
    ParityCaseConfig(
        case_id="C1",
        model="Phi-tiny-MoE-instruct",
        mode="offline",
        scale_gpu=24,
        prefill_tokens=512,
        decode_tokens=128,
        num_requests=64,
        layer=ParityLayer.L1_DUMMY,
        description="MoE EP>1 event choreography consistency",
    ),
    ParityCaseConfig(
        case_id="C2",
        model="Phi-tiny-MoE-instruct",
        mode="offline",
        scale_gpu=24,
        prefill_tokens=512,
        decode_tokens=128,
        num_requests=64,
        layer=ParityLayer.L1_DUMMY,
        description="EP=1 lumped-path workflow verification",
    ),
    ParityCaseConfig(
        case_id="C3",
        model="step-moe-noquant",
        mode="offline",
        scale_gpu=24,
        prefill_tokens=512,
        decode_tokens=128,
        num_requests=8,
        layer=ParityLayer.L1_DUMMY,
        description="Mixed-layer boundary trace",
    ),
    ParityCaseConfig(
        case_id="C4",
        model="step-moe-noquant",
        mode="offline",
        scale_gpu=24,
        prefill_tokens=512,
        decode_tokens=128,
        num_requests=64,
        layer=ParityLayer.L2_TRAINED,
        description="Baseline single-lane MoE parity",
    ),
    ParityCaseConfig(
        case_id="C5",
        model="step-moe-noquant",
        mode="online",
        scale_gpu=24,
        prefill_tokens=512,
        decode_tokens=128,
        num_requests=64,
        qps=2.0,
        layer=ParityLayer.L2_TRAINED,
        description="Online mode parity",
    ),
    ParityCaseConfig(
        case_id="C6",
        model="step-moe-noquant",
        mode="offline",
        scale_gpu=32,
        prefill_tokens=512,
        decode_tokens=128,
        num_requests=64,
        layer=ParityLayer.L2_TRAINED,
        description="2 FFN lanes, DP=2 decode-attn",
    ),
    ParityCaseConfig(
        case_id="C7",
        model="step-moe-noquant",
        mode="online",
        scale_gpu=32,
        prefill_tokens=512,
        decode_tokens=128,
        num_requests=64,
        qps=2.0,
        layer=ParityLayer.L2_TRAINED,
        description="Multi-lane online",
    ),
    ParityCaseConfig(
        case_id="C8",
        model="step-moe-noquant",
        mode="offline",
        scale_gpu=32,
        prefill_tokens=2048,
        decode_tokens=256,
        num_requests=64,
        layer=ParityLayer.L2_TRAINED,
        description="Long prompt",
    ),
    ParityCaseConfig(
        case_id="C9",
        model="step-moe-noquant",
        mode="online",
        scale_gpu=64,
        prefill_tokens=2048,
        decode_tokens=256,
        num_requests=256,
        qps=8.0,
        layer=ParityLayer.L2_TRAINED,
        description="4 FFN lanes, 2 prefill reps, EP=16, high load",
    ),
    ParityCaseConfig(
        case_id="C10",
        model="step-moe-noquant",
        mode="offline",
        scale_gpu=32,
        prefill_tokens=512,
        decode_tokens=128,
        num_requests=64,
        cuda_graph=True,
        layer=ParityLayer.L2_TRAINED,
        description="CUDA graph parity",
    ),
    ParityCaseConfig(
        case_id="C11",
        model="step-moe-noquant",
        mode="online",
        scale_gpu=32,
        prefill_tokens=512,
        decode_tokens=128,
        num_requests=64,
        qps=2.0,
        cuda_graph=True,
        layer=ParityLayer.L2_TRAINED,
        description="CUDA graph online",
    ),
    ParityCaseConfig(
        case_id="C12",
        model="llama2_7b_dense_example",
        mode="offline",
        scale_gpu=24,
        prefill_tokens=512,
        decode_tokens=128,
        num_requests=64,
        layer=ParityLayer.L2_TRAINED,
        description="Dense model parity (profiling-driven)",
    ),
    ParityCaseConfig(
        case_id="C13",
        model="llama2_7b_dense_example",
        mode="online",
        scale_gpu=24,
        prefill_tokens=512,
        decode_tokens=128,
        num_requests=64,
        qps=2.0,
        layer=ParityLayer.L2_TRAINED,
        description="Dense online parity",
    ),
    ParityCaseConfig(
        case_id="C14",
        model="llama2_7b_dense_example",
        mode="offline",
        scale_gpu=32,
        prefill_tokens=2048,
        decode_tokens=256,
        num_requests=64,
        layer=ParityLayer.L2_TRAINED,
        description="Dense long prompt + prefill PP=2",
    ),
    ParityCaseConfig(
        case_id="C15",
        model="Phi-tiny-MoE-instruct",
        mode="offline",
        scale_gpu=32,
        prefill_tokens=512,
        decode_tokens=128,
        num_requests=64,
        layer=ParityLayer.L1_DUMMY,
        description="2 FFN lanes workflow verification",
    ),
]


def get_case_by_id(case_id: str) -> ParityCaseConfig:
    """Look up a parity case by its ID (e.g., 'C4')."""
    for case in PARITY_CASES:
        if case.case_id == case_id:
            return case
    raise ValueError(f"Unknown parity case: {case_id}")
